information:
  port: 23333

mysql:
  path: '127.0.0.1'
  config: 'charset=utf8mb4&parseTime=true&loc=Local'
  db-name: 'mcs'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100

zap:
  dir: 'log'
  header: '[MCS_Server]'
  format: 'console'
  show-line: true