// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dept/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科室"
                ],
                "summary": "增加一个科室",
                "parameters": [
                    {
                        "description": "科室名称",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddDept"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"科室添加成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dept/deleteDept": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科室"
                ],
                "summary": "根据传入的科室结构体删除数据库中对应科室信息",
                "parameters": [
                    {
                        "description": "数据库中科室结构体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BaseDept"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"科室信息删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dept/listAll": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科室"
                ],
                "summary": "获取所有科室",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"科室信息获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/doctor/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "医生"
                ],
                "summary": "注册医生信息",
                "parameters": [
                    {
                        "description": "医生id，医生姓名，机构id，机构名称，科室id，科室名称，医生头像链接，医生职称代码，医生职称",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddDoctor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"医生注册成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/doctor/findByName": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "医生"
                ],
                "summary": "根据姓名模糊查询医生",
                "parameters": [
                    {
                        "description": "医生姓名",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FindDoctorByName"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"医生信息获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/doctor/listAll": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "医生"
                ],
                "summary": "获取所有医生信息",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"医生信息获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drug/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "药物"
                ],
                "summary": "增加一种药物",
                "parameters": [
                    {
                        "description": "药物通用名称,商品名,拼音码,药品规格,包装单位,药品价格,剂量,剂量单位,产地,批准文号",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddDrug"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"药物添加成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drug/deleteDrug": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "药物"
                ],
                "summary": "根据传入的药物结构体删除数据库中对应药物信息",
                "parameters": [
                    {
                        "description": "数据库中药物结构体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BaseDrug"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"药物信息删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drug/findByName": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "药物"
                ],
                "summary": "根据名称模糊查询药物",
                "parameters": [
                    {
                        "description": "药物名称",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FindDrugByName"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"药物信息获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drug/findByPinyin": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "药物"
                ],
                "summary": "根据拼音代码模糊查询药物",
                "parameters": [
                    {
                        "description": "药物拼音",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FindDrugByPinyin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"药物信息获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drug/listAll": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "药物"
                ],
                "summary": "获取所有药物信息",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"药物信息获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/organization/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "机构"
                ],
                "summary": "增加一个机构",
                "parameters": [
                    {
                        "description": "机构名称",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddOrg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"机构添加成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/organization/deleteOrg": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "机构"
                ],
                "summary": "根据传入的机构结构体删除数据库中对应机构信息",
                "parameters": [
                    {
                        "description": "数据库中机构结构体",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BaseOrg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"机构信息删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/organization/listAll": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "机构"
                ],
                "summary": "获取所有机构",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"机构信息获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BaseDept": {
            "type": "object",
            "properties": {
                "dept_id": {
                    "type": "integer"
                },
                "dept_name": {
                    "type": "string"
                }
            }
        },
        "model.BaseDrug": {
            "type": "object",
            "properties": {
                "approval_number": {
                    "type": "string"
                },
                "dose": {
                    "type": "number"
                },
                "dose_unit": {
                    "type": "string"
                },
                "drug_id": {
                    "type": "integer"
                },
                "drug_name": {
                    "type": "string"
                },
                "factory_name": {
                    "type": "string"
                },
                "pack_unit": {
                    "type": "string"
                },
                "pinyin_code": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "specification": {
                    "type": "string"
                },
                "trade_name": {
                    "type": "string"
                }
            }
        },
        "model.BaseOrg": {
            "type": "object",
            "properties": {
                "org_id": {
                    "type": "integer"
                },
                "org_name": {
                    "type": "string"
                }
            }
        },
        "request.AddDept": {
            "type": "object",
            "properties": {
                "dept_name": {
                    "type": "string"
                }
            }
        },
        "request.AddDoctor": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "dept_id": {
                    "type": "integer"
                },
                "dept_name": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "string"
                },
                "doctor_name": {
                    "type": "string"
                },
                "level_code": {
                    "type": "string"
                },
                "level_name": {
                    "type": "string"
                },
                "org_id": {
                    "type": "integer"
                },
                "org_name": {
                    "type": "string"
                }
            }
        },
        "request.AddDrug": {
            "type": "object",
            "properties": {
                "approval_number": {
                    "type": "string"
                },
                "dose": {
                    "type": "number"
                },
                "dose_unit": {
                    "type": "string"
                },
                "drug_name": {
                    "type": "string"
                },
                "factory_name": {
                    "type": "string"
                },
                "pack_unit": {
                    "type": "string"
                },
                "pinyin_code": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "specification": {
                    "type": "string"
                },
                "trade_name": {
                    "type": "string"
                }
            }
        },
        "request.AddOrg": {
            "type": "object",
            "properties": {
                "org_name": {
                    "type": "string"
                }
            }
        },
        "request.FindDoctorByName": {
            "type": "object",
            "properties": {
                "doctor_name": {
                    "type": "string"
                }
            }
        },
        "request.FindDrugByName": {
            "type": "object",
            "properties": {
                "drug_name": {
                    "type": "string"
                }
            }
        },
        "request.FindDrugByPinyin": {
            "type": "object",
            "properties": {
                "pinyin": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "x-token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger MCS_Server API",
	Description: "MCS_Server API 接口文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
